% Please note that: Running these codes will last from minutes to tens of minutes for outputting 
% the results of Quadratic SVM, Bagged Trees and scASK on 13 real single-cell datasets with data perturbation. 
% Due to the built-in cross validation or random resampling of some algorithms (such as Bagged Trees), 
% the running result may be slightly different from figure 7. For results without data perturbation, see figure 6
figure71,figure72,figure73,figure74,figure75,figure76,figure77,figure78,figure79,figure710,figure711,figure712,figure713

load('figure71.mat'); load('figure72.mat'); load('figure73.mat'); load('figure74.mat'); load('figure75.mat');
load('figure76.mat'); load('figure77.mat'); load('figure78.mat'); load('figure79.mat'); load('figure710.mat');
load('figure711.mat'); load('figure712.mat'); load('figure713.mat');

testingData_accuracy_rz_all=[[testingData_accuracy12_rz;testingData_accuracy15_rz;testingData_accuracy16_rz],...
    [testingData_accuracy22_rz;testingData_accuracy25_rz;testingData_accuracy26_rz],...
    [testingData_accuracy32_rz;testingData_accuracy35_rz;testingData_accuracy36_rz],...
    [testingData_accuracy42_rz;testingData_accuracy45_rz;testingData_accuracy46_rz],...
    [testingData_accuracy52_rz;testingData_accuracy55_rz;testingData_accuracy56_rz],...
    [testingData_accuracy62_rz;testingData_accuracy65_rz;testingData_accuracy66_rz],...
    [testingData_accuracy72_rz;testingData_accuracy75_rz;testingData_accuracy76_rz],...
    [testingData_accuracy82_rz;testingData_accuracy85_rz;testingData_accuracy86_rz],...
    [testingData_accuracy92_rz;testingData_accuracy95_rz;testingData_accuracy96_rz],...
    [testingData_accuracy102_rz;testingData_accuracy105_rz;testingData_accuracy106_rz],...
    [testingData_accuracy112_rz;testingData_accuracy115_rz;testingData_accuracy116_rz],...
    [testingData_accuracy122_rz;testingData_accuracy125_rz;testingData_accuracy126_rz],...
    [testingData_accuracy132_rz;testingData_accuracy135_rz;testingData_accuracy136_rz]];
openvar('testingData_accuracy_rz_all');
